### ISSUE TITLE
Wifi commands don't work

### ISSUE THREAD

**Issue by mich181189** [emfcamp/badge-2024-documentation#121]
In the documentation, it says 

```
# If connecting to non-wpa2enterprise networks
settings.set("wifi_wpa2ent_username", None)
```

however when I try that I get:

```
>>> settings.set("wifi_wpa2ent_username", None)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "settings.py", line 29, in set
KeyError: wifi_wpa2ent_username
>>>
```

For me this wasn't needed anyway.

**Comment by npentrel** [comment]
Clarified this here slightly, but yeah, only needed if you are on a WPA2 network
